spring:
  application:
    name: spring-boot-semestrovka
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_semestrovka
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  freemarker:
    template-loader-path: classpath:/templates/ftl
    suffix: .ftlh

