<#macro menu >
<div class="navbar">
    <div class="logo">
        <img src="https://catherineasquithgallery.com/uploads/posts/2021-02/1614543159_40-p-sobaki-na-belom-fone-53.png" alt="Logo">
    </div>
    <div class="menu">
        <a href="../profile/{user.id}">Home</a>
        <a href="#about">About</a>
        <a href="#services">Services</a>
        <a href="#contact">Contact</a>
    </div>
</div>
</#macro>
